### ISSUE TITLE
Temperature is no longer being returned in the get_readings / get_latest_readings call

### ISSUE THREAD

**Issue by 0bmay** [snjoetw/py-canary#12]
when the cal to get readings gets the readings to use, it uses a 2 hour window at 10 minute intervals to get data with. The resulting JSON from Canary lists 20 items, the first 12 are air quality, the next 8 are humidity. Temperature is not returned in the first 20 records. I don't know if Canary changed the order in which the data is returned (date-time vs sensor_type) but it appears to be sensor-type, then date desc.

This appears to be why temperature is missing. Changing the window of time to look at to 1 hour resulted in all three data types (air_quality, humidify and temperature) to be retuned in the Api.get_readings call.

I will attempt to fork the repo and submit a fix.. even if it's a singe character...

**Comment by gibbiemonster** [comment]
Somewhat related to https://github.com/home-assistant/core/issues/71273
